drop table user if exists;
create table user (
  	user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
	email varchar(25) not null,
	username varchar(16) not null,
  	password varchar(30) not null
);

drop table follower if exists;
	create table follower (
	follower_id integer,
	followee_id integer
);

drop table message if exists;
create table message (
 	content varchar(200) not null,
 	post_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
 	poster_id integer not null,
	date timestamp
);